### ISSUE TITLE
Take Theo off the group

### ISSUE THREAD

**Issue by joshwlambert** [Neves-P/merging_short_stories#11]
The changes in the story made by @TheoPannetier have been detrimental to the progress of the group. I therefore suggest that we release his duties.

**Comment by Neves-P** [comment]
:+1:

**Comment by TheoPannetier** [comment]
![do not want](http://3.bp.blogspot.com/_xFlKC0veggw/So3Duz90ejI/AAAAAAAAADE/yojL_8ns5Nk/s400/buyao.jpg)

**Comment by Neves-P** [comment]
:rofl:
